#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
	path:	    /logout
	methods:    GET*

pokemon: 
	path:	    /logout
	methods:    GET
	controller: App\Controller\PokemonController::index

starter: 
	path:	    /starter
	methods:    GET
	controller: App\Controller\StarterController::index

Dresseur: 
	path:	    /Dresseur
	methods:    GET
	controller: App\Controller\::index
